#!/bin/sh

################################################################################
# Copyright (c) 2015-2019 Skymind, Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

mkdir vizdoom
cd ..
git clone https://github.com/Marqt/ViZDoom
cd VizDoom
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_JAVA=ON
make
cp bin/java/libvizdoom.so ../rl4j-examples/vizdoom/
cp bin/java/vizdoom.jar ../rl4j-examples/vizdoom/
cp bin/vizdoom ../rl4j-examples/vizdoom/
cp bin/vizdoom.pk3 ../rl4j-examples/vizdoom/
cp -r scenarios/ ../rl4j-examples/vizdoom/
cd ../rl4j-examples/
export MAVEN_OPTS="-Djava.library.path=vizdoom -Xmx30g"
mvn clean compile exec:java -Dexec.mainClass="org.deeplearning4j.rl4j.Doom"
