on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build and test all modules
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn --version
          for folder in $(ls); do
             if  [ -d "$folder" ] && [ "$folder" != "mvn-project-template" ] && [ "$folder" != "android-examples" ] && [ "$folder" != "oreilly-book-dl4j-examples" ]; then
               cd "$folder"
               if test -f "pom.xml"; then
                  mvn clean test
               fi
               cd ..
             fi
          done
